### ISSUE TITLE
Intern tasks

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/dtk#96]
```[tasklist]
### Tasks
- [ ] 清理编译警告，减少 Dtk 相关项目编译过程中出现的编译警告，包括不限于使用 Qt5/Qt6 编译时使用的一些废弃接口替换成新的接口
- [ ] 使用分析工具（静态分析如cppcheck/Valgrid等，安全检查如缓冲区溢出等）分析 Dtk 项目并处理相关警告
- [ ] 给 Dtk 相关项目新增单元测试
- [ ] https://github.com/linuxdeepin/dtk/issues/94
- [ ] https://github.com/linuxdeepin/dtk/issues/95
- [ ] 修复 Dtk/Issues 中未修复的 Bug
- [ ] https://github.com/linuxdeepin/dtk/issues/66
```
